kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "PortForwardWebsockets": true
nodes:
- role: control-plane
  image: kindest/node:latest
- role: worker
  image: kindest/node:latest
- role: worker
  image: kindest/node:latest

